import mongoose from "mongoose";


const employeeSchema = new mongoose.Schema({
    name: { type: String, required: true },
    // position: { type: String },
    workMobile: { type: String, required: true },
    workPhone: { type: String, required: true },
    workEmail: { type: String, required: true },
    department: { type: String, required: true },
    jobPosition: { type: String, required: true },
    manager: { type: String, required: true },
    coach: { type: String, required: true },
    resume: { type: String, required: true },
    skills: { type: [String], required: true },
    workAddress: { type: String, required: true },
    workLocation: { type: String, required: true },
    expenseApprover: { type: String, required: true },
    timeOffApprover: { type: String, required: true },
    workingHours: { type: String, required: true },
    timezone: { type: String, required: true },
    address: { type: String, required: true },
    email: { type: String, required: true },
    phone: { type: String, required: true },
    homeWorkDistance: { type: String, required: true },
    privateCarPlate: { type: String, required: true },
    maritalStatus: { type: String, required: true },
    dependentChildren: { type: String, required: true },
    certificateLevel: { type: String, required: true },
    fieldOfStudy: { type: String, required: true },
    school: { type: String, required: true },
    emergencyContactName: { type: String, required: true },
    emergencyContactPhone: { type: String, required: true },
    nationality: { type: String, required: true },
    identificationNo: { type: String, required: true },
    passportNo: { type: String, required: true },
    gender: { type: String, required: true },
    dateOfBirth: { type: String, required: true },
    placeOfBirth: { type: String, required: true },
    countryOfBirth: { type: String, required: true },
    nonResident: { type: String, required: true },
    employeeType: { type: String, required: true },
    relatedUser: { type: String, required: true },
    registrationNumber: { type: String, required: true },
    jobPosition: { type: String, required: true },
    hourlyCost: { type: String, required: true },
    fleetMobilityCard: { type: String, required: true },
    pinCode: { type: String, required: true },
    badgeID: { type: String, required: true },
  },{timestamps:true});
  
  export const Employee = mongoose.model('Employee', employeeSchema);